# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 8081
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: scott.toews@gov.bc.ca
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-http-and-https-pgadmin
spec:
  podSelector:
    matchLabels:
      app: pgadmin
  ingress:
  - ports:
    - protocol: TCP
      port: 8081
    - protocol: TCP
      port: 443
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pgadmin-route
spec:
  host: pgadmin.ca94a8-tools.apps.silver.devops.gov.bc.ca
  to:
    kind: Service
    name: pgadmin-service
  port:
    targetPort: 8081
