# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        role: frontend
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 8081
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: scott.toews@gov.bc.ca
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-root-password
          volumeMounts:
          - mountPath: /var/log/pgadmin
            name: pgadmin-storage
      volumes:
        - name: pgadmin-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  ports:
    - name: http81
      protocol: TCP
      port: 8081
      targetPort: 8081
      # nodePort: 30000
  selector:
    app: pgadmin
    role: frontend
  type: ClusterIP

---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: allow-http-and-https-pgadmin
# spec:
#   podSelector:
#     matchLabels:
#       app: pgadmin
#   ingress:
#   - ports:
#     - protocol: TCP
#       port: 8081
#     - protocol: TCP
#       port: 443
# ---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pgadmin-route
  labels:
    app: pgadmin
spec:
  host: pgadmin-ca94a8-tools.apps.silver.devops.gov.bc.ca
  to:
    kind: Service
    name: pgadmin-service
    weight: 100
  port:
    targetPort: http81
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
