# @format

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploy-template
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: '${APP_NAME}-app'
      namespace: '${NAMESPACE}'
      labels:
        app: '${APP_NAME}-app'
        deployment: '${APP_NAME}-app'
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: '${APP_NAME}-app'
          deployment: '${APP_NAME}-app'
      template:
        metadata:
          labels:
            app: '${APP_NAME}-app'
            deployment: '${APP_NAME}-app'
            role: frontend
        spec:
          containers:
            - name: '${APP_NAME}-app'
              image: 'ghcr.io/bcgov/${APP_NAME}-app:${TAG}'
              ports:
                - containerPort: ${PORT}
                  protocol: TCP
  - kind: Service
    apiVersion: v1
    metadata:
      name: '${APP_NAME}-app'
      namespace: '${NAMESPACE}'
      labels:
        app: '${APP_NAME}-app'
    spec:
      ports:
        - name: ${PORT}-tcp
          protocol: TCP
          port: ${PORT}
          targetPort: ${PORT}
      selector:
        app: '${APP_NAME}-app'
        deployment: '${APP_NAME}-app'
        role: frontend
      type: ClusterIP
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: '${APP_NAME}-app'
      namespace: '${NAMESPACE}'
      labels:
        app: '${APP_NAME}-app'
    spec:
      host: '${APP_NAME}-${NAMESPACE}.apps.silver.devops.gov.bc.ca'
      to:
        kind: Service
        name: '${APP_NAME}-app'
        weight: 100
      port:
        targetPort: ${PORT}-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
parameters:
  - name: APP_NAME
    displayName: Application Name
    required: true
  - name: NAMESPACE
    displayName: Namespace
    required: true
  - name: TAG
    displayName: Tag for github container registry
    required: false
    value: latest
  - name: PORT
    displayName: exposed port
    required: true
