name: Build and deploy
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: false
        default: 'tools'
      APP_NAME:
        required: true
        type: string

jobs:
  Setup:
    environment: ${{ inputs.ENVIRONMENT }}
    name: Setup Runner
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - run: |
          ls -l
          echo ${{ inputs.APP_NAME }}
