# @format

name: Build-name
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: false
      APP_NAME:
        required: true
        type: string
      APP_PATH:
        required: true
        type: string
      PORT:
        required: false
        type: number
        default: 8080
      IMAGE_TAGS:
        required: false
        type: string
        default: 'tag'
    outputs:
      registry-path:
        value: ${{ jobs.Build.outputs.registry-path }}

jobs:
  Build:
    name: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      registry-path: ${{ steps.push-image.outputs.registry-path }}
      image: ${{ steps.build-image.outputs.image }}
      tags: ${{ steps.build-image.outputs.tags }}

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node modules
        id: npmCacheStep
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ secrets.CACHE_VERSION }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        if: steps.npmCacheStep.outputs.cache-hit != 'true'
        run: npm install --production --silent

      - name: check contexts
        env:
          MY_CONTEXT: ${{ toJSON(github) }}
        run: echo "$MY_CONTEXT"
      - name: check contexts
        env:
          MY_CONTEXT: ${{ toJSON(job) }}
        run: echo "$MY_CONTEXT"
      - name: check contexts
        env:
          MY_CONTEXT: ${{ toJSON(env) }}
        run: echo "$MY_CONTEXT"
      - name: check contexts
        env:
          MY_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$MY_CONTEXT"
      - name: check contexts
        env:
          MY_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "$MY_CONTEXT"
      - name: check contexts
        env:
          MY_CONTEXT: ${{ toJSON(secrets) }}
        run: echo "$MY_CONTEXT"
        
      - name: Install Nx package
        run: npm install @nrwl/cli --silent

      - name: Build application
        run: npx nx build  ${{ inputs.APP_NAME }}

      - name: checkup
        run: ls -l dist/apps/slam

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ inputs.APP_NAME }}
          tags: ${{ inputs.IMAGE_TAGS }}
          dockerfiles: ${{ inputs.APP_PATH }}/Dockerfile

      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
