name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  slam-backend:
    name: SLAM API Server
    uses: bcgov/citz-imb/.github/workflows/Build-deploy.yml@e605c11131c2e6ff593746335772f295434577f6
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT: 3333

  slam-frontend:
    name: SLAM frontend
    uses: bcgov/citz-imb/.github/workflows/Build-deploy.yml@e605c11131c2e6ff593746335772f295434577f6
    with:
      APP_NAME: slam-app
      APP_PATH: ./apps/slam/app
