name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build-slam-backend:
    name: Build SLAM API Server
    uses: bcgov/citz-imb/.github/workflows/Build.yml@27661924ef430ff458b39c722c8a1840e0a739d5
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT: 3333
