name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build-slam-backend:
    name: SLAM-API
    uses: bcgov/citz-imb/.github/workflows/Build.yml@f64af25a5087af0652810c58bb35b8422b8d0d1a
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT: 3333

  test-output:
    name: test
    runs-on: ubuntu-latest
    environment: tools

    steps:
      - runs: |
        echo ${{ needs.build-slam-backend.outputs.registry-path }}