name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build-slam-backend:
    name: SLAM-API
    uses: bcgov/citz-imb/.github/workflows/Build.yml@
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT: 3333

  deploy-slam-backend-tools:
    needs: [build-slam-backend]
    name: SLAM-API
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: tools
      REGISTRY_PATH: ${{ needs.build-slam-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
