# @format

name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build-slam-backend:
    name: SLAM-API
    uses: bcgov/citz-imb/.github/workflows/Build.yml@d6bec8873b8d2be234ca22dd6c2af8cab3667a2e
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT: 3333

  test-output:
    needs: [build-slam-backend]
    name: test
    runs-on: ubuntu-latest
    environment: tools

    steps:
      - run: echo ${{ needs.build-slam-backend.outputs.registry-path }}
