# @format

name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]

# apps with environments: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}],"ENVIRONMENTS":["dev","test","prod"]}'
# apps without environments: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'

jobs:
  checkenv:
    runs-on: ubuntu-20.04
    steps:
      - run: env

  # build:
  #   name: Image Build
  #   uses: bcgov/citz-imb/.github/workflows/Build.yml@main
  #   with:
  #     MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
  #     OS: ubuntu-20.04

  # test:
  #   name: Testing
  #   needs: build
  #   uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
  #   with:
  #     MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
  #     OS: ubuntu-20.04

  deploy-dev:
    name: Dev
    # needs: [build, test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04
      ENVIRONMENT: dev
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}

  deploy-test:
    if: contains(github.event.head_commit.message, '#release')
    name: Test
    needs: [deploy-dev]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04
      ENVIRONMENT: test
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}

  deploy-prod:
    if: contains(github.event.head_commit.message, '#release')
    name: Prod
    needs: [deploy-test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04
      ENVIRONMENT: prod
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}
