# @format

name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]

env:
  runner: ubuntu-20.04
  apps: '[{"name":"slam-api","path":"./apps/slam/api"},{"name:":"slam-app","path":"./apps/slam/app"}]'
  environments: '["dev"]'

jobs:
  show:
    uses: bcgov/citz-imb/.github/workflows/Test.yml@main
    with:
      APPS: '[{"name:","slam-api},{"name":"slam-app"}]'
      ENVIRONMENTS: '["dev","test","prod"]'
      RUNNER: ubuntu-20.04

  # tests:
  #   name: Unit Tests
  #   uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
  #   with:
  #     APPS: '["slam-api,"slam-app"]'
  #     ENVIRONMENTS: '["dev","test","prod"]'