# @format

name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]

env:
  OS: ${{ 'ubuntu-20.04' }}

jobs:
  checkenv:
    runs-on: ubuntu-latest
    steps:
      - run: env

  show:
    uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
    with:
      APPS: '[{"name":"slam-api},{"name":"slam-app"}]'
      ENVIRONMENTS: '["dev","test","prod"]'
      OS: env.OS

  # tests:
  #   name: Unit Tests
  #   uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
  #   with:
  #     APPS: '["slam-api,"slam-app"]'
  #     ENVIRONMENTS: '["dev","test","prod"]'
