# @format

name: CICD

on:
  push:
    branches:
      - mainx
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [mainx]
  workflow_dispatch:

concurrency:
  group: citz-imb-CICD
  cancel-in-progress: false

jobs:
  commit-data:
    runs-on: ubuntu-20.04
    outputs:
     short_sha: ${{ steps.commit-data.outputs.short_sha }}
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Get commit short-sha
        id: commit-data
        uses: redhat-actions/common/commit-data@v1
      - name: echo steps
        run: echo '${{ toJSON(steps) }}'

  build:
    name: Image Build
    needs: commit-data
    uses: bcgov/citz-imb/.github/workflows/Build.yml@main
    with:
      MATRIX_INCLUDE: '{"APP-NAME": ["slam"],"APP-TYPE": ["api", "app"]}"'
      OS: ubuntu-20.04
      TAG: ${{ needs.commit-data.outputs.short_sha}}

  test:
    name: Testing
    needs: build
    uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04

  deploy-dev:
    name: Deploy Dev
    needs: [commit-data, build, test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04
      ENVIRONMENT: dev
      TAG: ${{ needs.commit-data.outputs.short_sha}}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}

  deploy-test:
    if: contains(github.event.head_commit.message, '#label release')
    name: Deploy Test
    needs: [commit-data, deploy-dev]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04
      ENVIRONMENT: test
      TAG: ${{ needs.commit-data.outputs.short_sha}}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}

  deploy-prod:
    if: contains(github.event.head_commit.message, '#label release')
    name: Deploy Prod
    needs: [commit-data, deploy-test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      MATRIX_INCLUDE: '{"APPS":[{"name":"slam-api","path":"./apps/slam/api"},{"name":"slam-app","path":"./apps/slam/app"}]}'
      OS: ubuntu-20.04
      ENVIRONMENT: prod
      TAG: ${{ needs.commit-data.outputs.short_sha}}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}
