# @format

name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]

env:
  runner: ubuntu-20.04

jobs:
  firstjob:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix}}
    steps:
      - name: Set Dynamic Matrix
        id: setmatrix
        run: |
          matrixStringifiedObject='{"include":[{"app":{"name":"slam-api"}},{"app":{"name:":"slam-app"}}]}'
          echo "::set-output name=matrix::$matrixStringifiedObject"

  secondjob:
    needs: firstjob
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{fromJson(needs.firstjob.outputs.matrix)}}
    steps:
      - run: echo Run ${{matrix.app.name}}

  # test:
  #   name: slam-api
  #   needs: [firstjob]
  #   strategy:
  #     matrix: ${{fromJson(needs.firstjob.outputs.matrix)}}
  #   uses: bcgov/citz-imb/.github/workflows/Test.yml@main
  #   with:
  #     APP_NAME: ${{matrix.appname}}
  #     APP_PATH: ./apps/slam/api
  #     PORT: 3333