# @format

name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]

jobs:
  checkenv:
    runs-on: ubuntu-20.04
    steps:
      - run: env

  show:
    uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
    with:
      MATRIX_INCLUDE: '{"include":[{"apps":{"name":"slam-api","path":"./apps/slam/api"}},{"apps":{"name:":"slam-app","path":"./apps/slam/app"}},{"ENVIRONMENTS":"dev"},{"ENVIRONMENTS":"test"},{"ENVIRONMENTS":"prod"}]}'
      OS: ubuntu-20.04

  # tests:
  #   name: Unit Tests
  #   uses: bcgov/citz-imb/.github/workflows/UnitTest.yml@main
  #   with:
  #     APPS: '["slam-api,"slam-app"]'
  #     ENVIRONMENTS: '["dev","test","prod"]'
