# @format

name: Deploy
on:
  workflow_call:
    inputs:
      MATRIX_INCLUDE:
        required: true
        type: string
      OS:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  Deploy:
    name: ${{ matrix.APPS.name }}-${{ matrix.ENVIRONMENTS }}
    runs-on: ${{ inputs.OS }}
    strategy:
      matrix: ${{fromJSON(inputs.MATRIX_INCLUDE)}}
    environment: ${{ matrix.ENVIRONMENTS }}

    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Deploy
        id: deploy-and-expose
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ matrix.APPS.name }}
          image: ${{ inputs.REGISTRY_PATH }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
          port: ${{ inputs.PORT }}

      - name: Apply Labels
        run: |
          echo "app_name: ${{ matrix.APPS.name }}"
          oc label pod -l deployment=${{ matrix.APPS.name }} role=frontend

      # Perform a (very) basic integration test.
      # This step is retried since the time to pull the image and start the pod can vary.
      - name: Test project is running
        id: test-project
        uses: nick-invision/retry@v2.2.0
        with:
          timeout_seconds: 5
          retry_wait_seconds: 10
          max_attempts: 100
          warning_on_retry: false
          # Just check that the root endpoint returns a success status (-f flag).
          command: curl -sSfLi ${{ steps.deploy-and-expose.outputs.route }}
