# @format

name: Deploy
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: false
        default: 'tools'
      APP_NAME:
        required: true
        type: string
      PORT:
        required: false
        type: number
        default: 8080
      REGISTRY_PATH:
        required: true
        type: string
    secrets:
      OPENSHIFT_SERVER:
        required: true
      OPENSHIFT_TOKEN:
        required: true
      OPENSHIFT_NAMESPACE:
        required: true

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Deploy
        id: deploy-and-expose
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ inputs.APP_NAME }}
          image: ${{ inputs.REGISTRY_PATH }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
          port: ${{ inputs.PORT }}
          label: role=frontend
