name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build slam-api Docker image
      run: docker build ./apps/api/slam --tag citz-imb/slam-api:0.0.0
    - name: Build slam-api Docker image
      run: docker build ./apps/slam --tag citz-imb/slam:0.0.0
