name: Docker Image CI

on:
  push:
    branches: [ mainx ]
  pull_request:
    branches: [ mainx ]

jobs:

  build docker image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build slam-api Docker image
      run: |
        docker build ./apps/api/slam -t citz-imb/slam-api:0.0.0
#    - name: Build slam Docker image
#      run: |
#        docker build ./apps/slam -t citz-imb/slam:0.0.0
