name: OpenShift-CI
on:
  push:
    branches: [ main ]

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
  APP_NAME: 'api-slam'
  API_SLAM_PORT: 8080
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: 'tag'

jobs:
  Build-and-register-image:
    runs-on: ubuntu-latest
    environment: tools

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Cache node modules
        id: npmCacheStep
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        if: steps.npmCacheStep.outputs.cache-hit != 'true'
        run: npm install --production --silent

      - name: Install nx cli
        run: npm install @nrwl/cli --silent

      - name: Build application
        run: npx nx build

      - run: |
          ls -l
          ls -l ./apps/slam/api

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          dockerfiles: ./apps/slam/api/Dockerfile

      # - name: Push to registry
      #   id: push-image
      #   uses: redhat-actions/push-to-registry@v2
      #   with:
      #     image: ${{ steps.build-image.outputs.image }}
      #     tags: ${{ steps.build-image.outputs.tags }}
      #     registry: ${{ env.IMAGE_REGISTRY }}
      #     username: ${{ env.IMAGE_REGISTRY_USER }}
      #     password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

      # - name: Log in to OpenShift
      #   uses: redhat-actions/oc-login@v1
      #   with:
      #     openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
      #     openshift_token: ${{ env.OPENSHIFT_TOKEN }}
      #     insecure_skip_tls_verify: true
      #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      # - name: Create and expose app
      #   id: deploy-and-expose
      #   uses: redhat-actions/oc-new-app@v1
      #   with:
      #     app_name: ${{ env.APP_NAME }}
      #     image: ${{ steps.push-image.outputs.registry-path }}
      #     namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      #     port: ${{ env.API_SLAM_PORT }}