name: OpenShift-CI
on:
  push:
    branches: [ mainx ]

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
  APP_NAME: 'api-slam'
  API_SLAM_PORT: 8080
  # IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY: registry.access.redhat.com/ubi8/nodejs-14
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  # IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.OPENSHIFT_TOKEN }}
  IMAGE_TAGS: 'tag'

jobs:
  Build-and-register-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{steps.push-image.outputs}}
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install packages
        run: |
          npm install --production --silent
          npm install @nrwl/cli --silent

      - name: Build application
        run: |
          npx nx build

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          dockerfiles: |
            ./apps/api/slam/Dockerfile

      - name: Install OC
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - run: |
          oc project ca94a8-tools

      - name: Push to registry
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_REGISTRY_USER }}
          password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

      # - name: Push to registry
      #   id: push-image
      #   uses: redhat-actions/push-to-registry@v2
      #   with:
      #     image: ${{ steps.build-image.outputs.image }}
      #     tags: ${{ steps.build-image.outputs.tags }}
      #     registry: ${{ env.IMAGE_REGISTRY }}
      #     username: ${{ env.IMAGE_REGISTRY_USER }}
      #     password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

  # Deploy-to-OpenShift:
  #   runs-on: ubuntu-latest
  #   needs: [Build-and-register-image]
  #   environment: Tools

  #   steps:
  #     - name: Install OC
  #       uses: redhat-actions/openshift-tools-installer@v1
  #       with:
  #         oc: 4

  #     - name: Log in to OpenShift
  #       uses: redhat-actions/oc-login@v1
  #       with:
  #         openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
  #         openshift_token: ${{ env.OPENSHIFT_TOKEN }}
  #         insecure_skip_tls_verify: true
  #         namespace: ${{ env.OPENSHIFT_NAMESPACE }}

  #     - name: Create and expose app
  #       id: deploy-and-expose
  #       uses: redhat-actions/oc-new-app@v1
  #       with:
  #         app_name: ${{ env.APP_NAME }}
  #         image: ${{ build-image.steps.push-image.outputs.registry-path }}
  #         namespace: ${{ env.OPENSHIFT_NAMESPACE }}
  #         port: ${{ env.API_SLAM_PORT }}