# @format

name: slam-app CICD Pipeline

env:
  MY_APP: slam-app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    # name: slam-app
    uses: bcgov/citz-imb/.github/workflows/Build.yml@main
    with:
      APP_NAME: slam-app
      APP_PATH: ./apps/slam/app
      PORT: 3000
      # IMAGE_TAGS: role=frontend

  test:
    name: slam-app
    needs: [build]
    uses: bcgov/citz-imb/.github/workflows/Test.yml@main
    with:
      APP_NAME: slam-app
      APP_PATH: ./apps/slam/app
      PORT: 3000

  deploy-dev:
    name: slam-app
    needs: [build, test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-app
      PORT: 3000
      ENVIRONMENT: dev
      REGISTRY_PATH: ${{ needs.build.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-test:
    if: startsWith(github.event.head_commit.message, 'IOD') && contains(github.event.head_commit.message, '#ready-for-review')
    name: slam-app
    needs: [build, deploy-dev]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-app
      PORT: 4200
      ENVIRONMENT: test
      REGISTRY_PATH: ${{ needs.build.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  send-notification-test:
    name: Notify Teams
    needs: [deploy-test]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: 'slam-app successfully deployed to test'

  deploy-prod:
    name: slam-app
    needs: [build, deploy-test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-app
      PORT: 4200
      ENVIRONMENT: prod
      REGISTRY_PATH: ${{ needs.build.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  send-notification-prod:
    name: Notify Teams
    needs: [deploy-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: 'slam-app successfully deployed to production'
