# @format

name: ${{ env.APP_NAME }} CICD Pipeline
on:
  push:
    branches: [main]

jobs:
  env:
    APP_NAME: slam-api
    APP_PATH: ./apps/slam/api
    PORT: 3333

  build-backend:
    name: ${{ env.APP_NAME }}
    uses: bcgov/citz-imb/.github/workflows/Build.yml@d6bec8873b8d2be234ca22dd6c2af8cab3667a2e
    with:
      APP_NAME: ${{ env.APP_NAME }}
      APP_PATH: ${{ env.APP_PATH }}
      PORT:  ${{ env.PORT }}

  deploy-backend-tools:
    needs: [build-backend]
    name: ${{ env.APP_NAME }}
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@1ff3c6908ae2679d5047051887290ec03770a516
    with:
      APP_NAME: ${{ env.APP_NAME }}
      PORT: ${{ env.PORT }}
      ENVIRONMENT: tools
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-dev:
    needs: [build-backend]
    name: ${{ env.APP_NAME }}
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@1ff3c6908ae2679d5047051887290ec03770a516
    with:
      APP_NAME: ${{ env.APP_NAME }}
      PORT: ${{ env.PORT }}
      ENVIRONMENT: dev
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-test:
    needs: [build-backend]
    name: ${{ env.APP_NAME }}
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@1ff3c6908ae2679d5047051887290ec03770a516
    with:
      APP_NAME: ${{ env.APP_NAME }}
      PORT: ${{ env.PORT }}
      ENVIRONMENT: test
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-prod:
    needs: [build-backend]
    name: ${{ env.APP_NAME }}
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@1ff3c6908ae2679d5047051887290ec03770a516
    with:
      APP_NAME: ${{ env.APP_NAME }}
      PORT: ${{ env.PORT }}
      ENVIRONMENT: prod
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
