name: CICD Pipeline
on:
  push:
    branches: [mainx]
  pull_request:
    branches: [mainx]

jobs:
  build-backend:
    name: Build & Register
    uses: bcgov/citz-imb/.github/workflows/Build.yml@main
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT:  3333

  deploy-backend-tools:
    name: Deploy
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: tools
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-dev:
    name: Deploy
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: dev
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-test:
    name: Deploy
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: test
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  send-notification-test:
    name: Notify Teams
    needs: [build-backend, deploy-backend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: "slam-api successfully deployed to test"

  deploy-backend-prod:
    name: Deploy
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: prod
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  send-notification-prod:
    name: Notify Teams
    needs: [build-backend, deploy-backend-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: "slam-api successfully deployed to production"