# @format

name: slam-api CICD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Application
    uses: bcgov/citz-imb/.github/workflows/Build.yml@main
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT: 3333

  deploy-dev:
    name: Dev
    needs: [build]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: dev
      REGISTRY_PATH: ${{ needs.build.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-test:
    if: startsWith(github.event.head_commit.message, 'iod') && contains(github.event.head_commit.message, 'done')
    name: Test
    needs: [build, deploy-dev]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: test
      REGISTRY_PATH: ${{ needs.build.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  send-notification-test:
    name: Notify Teams
    needs: [deploy-test]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: 'slam-api successfully deployed to test'

  deploy-prod:
    name: Production
    needs: [deploy-test]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: prod
      REGISTRY_PATH: ${{ needs.build.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  send-notification-prod:
    name: Notify Teams
    needs: [deploy-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Teams
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: 'slam-api successfully deployed to production'
