name: CICD Pipeline
on:
  push:
    branches: [main]

jobs:
  build-backend:
    uses: bcgov/citz-imb/.github/workflows/Build.yml@main
    with:
      APP_NAME: slam-api
      APP_PATH: ./apps/slam/api
      PORT:  3333

  deploy-backend-tools:
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: tools
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-dev:
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: dev
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  deploy-backend-test:
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: test
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  # send-notification-test:
  #   needs: [build-backend, deploy-backend-test]
  #   uses: thechetantalwar/teams-notify@v2
  #   with:
  #     teams_webhook_url: ${{ secrets.TEAM_HOOK }}
  #     message: "slam-api successfully deployed to test"

  deploy-backend-prod:
    needs: [build-backend]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      APP_NAME: slam-api
      PORT: 3333
      ENVIRONMENT: prod
      REGISTRY_PATH: ${{ needs.build-backend.outputs.registry-path }}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  # send-notification-prod:
  #   needs: [build-backend, deploy-backend-prod]
  #   uses: thechetantalwar/teams-notify@v2
  #   with:
  #     teams_webhook_url: ${{ secrets.TEAM_HOOK }}
  #     message: "slam-api successfully deployed to prod"
