name: GitHub Actions Demo

on:
  push:
    branches: [ main ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." #push
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!" #Linux
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}." # refs/heads/main # bcgov/citz-imb
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} -a
      - name: ENV
        run: env
      - run: echo "🍏 This job's status is ${{ job.status }}." # success

  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send a Notification
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Github Action Build Number ${{ github.run_number }} Completed for ${{ github.repository }} and the outcome is  ${{ needs.build.result }}."
