# @format
# checkout https://github.com/redhat-actions/crda

name: Test

env:
  myName: McTester
  myOtherName: ${{ 'Other McTester' }}

on:
  workflow_call:
    inputs:
      ENVIRONMENTS:
        type: string
        required: true
      APP_NAME:
        required: true
        type: string
      APP_PATH:
        required: false
        type: string
      PORT:
        required: false
        type: number
        default: 8080
      IMAGE_TAGS:
        required: false
        type: string
        default: 'latest'

jobs:
  Unit-Tests:
    name: My name is Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: echo "$ENV_CONTEXT"