on:
  push:
    branches: [ main ]

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
  APP_NAME: 'hello'
  APP_PORT: '4444'
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: ''

jobs:
  build-tools:
    runs-on: ubuntu-latest
    environment: Tools

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-verions: '16'

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
