name: GitHub Actions Demo
on: [push]
jobs:
   build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/.pipeline
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Build
        run: |
          oc version
          oc login --token=${{ secrets.OPENSHIFT_TOKEN}} --server=${{ secrets.OPENSHIFT_SERVER }}
          npm ci
          npm install @nrwl/cli --silent
          npx nx build
        env:
          CI: "true"
