# @format
# checkout https://github.com/redhat-actions/crda

name: Test

env:
  myName: McTester
  myOtherName: ${{ 'Other McTester' }}

on:
  workflow_call:
    inputs:
      ENVIRONMENTS:
        type: string
        required: true
      APPS:
        required: true
        type: string
      RUNNER:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  Unit-Tests:
    name: My name is Unit Test
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
        run: echo "$ENV_CONTEXT"
      - name: Dump input context
        env:
          INPUT_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "$INPUT_CONTEXT"
      - name: App deconstruction
        id: app_decon
        env:
          APPS_CONTEXT: ${{ toJSON(inputs.APPS)}}
        run: echo "::set-output name=myapps::$APPS_CONTEXT"
      - name: APP Presentation
        env:
          STEPS_CONTEXT: ${{ toJSON(steps.app_decon.outputs) }}
        run: echo "$STEPS_CONTEXT"