# @format

name: Test

on:
  workflow_call:
    inputs:
      APPS:
        required: true
        type: string
      ENVIRONMENTS:
        required: true
        type: string
      RUNNER:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  Unit-Tests:
    name: ${{ matrix.APPS }}
    runs-on: ${{ inputs.RUNNER }}
    strategy:
      matrix:
        APPS: ${{ fromJson(inputs.APPS) }}
        ENVIRONMENTS: ${{ fromJson(inputs.ENVIRONMENTS) }}
    steps:
      - run: echo ${{ matrix.APPS }} ${{ matrix.ENVIRONMENTS }}
