# @format

name: Test

on:
  workflow_call:
    inputs:
      APPS:
        required: true
        type: string
      ENVIRONMENTS:
        required: true
        type: string
      RUNNER:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  Unit-Tests:
    name: ${{ matrix.APPS }}
    runs-on: ${{ inputs.RUNNER }}
    strategy:
      matrix:
        APPS: ['slam-api', 'slam-app']
        ENVIRONMENTS: ['dev', 'test', 'prod']
    steps:
      - name: echo params
        run: echo "${{ matrix.APPS }} ${{ matrix.ENVIRONMENTS }}"

      - name: echo inputs
        run: echo "${{ toJSON(inputs)}}"
